stages:
  prepare_data:
    cmd: python src/01_prepare.py --configs=configs/configs.yaml --params=params.yaml
    deps:
      - src/01_prepare.py
      - data/data.xml
      - src/utils/common.py
      - src/utils/data_mgmt.py
      - configs/configs.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize:
    cmd: python src/02_featurization.py --configs=configs/configs.yaml --params=params.yaml
    deps:
      - src/02_featurization.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/configs.yaml
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl

  train:
    cmd: python src/03_train.py --configs=configs/configs.yaml --params=params.yaml
    deps:
      - src/03_train.py
      - artifacts/features/train.pkl
      - src/utils/common.py
      - configs/configs.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python src/04_evaluate.py --configs=configs/configs.yaml
    deps:
      - src/04_evaluate.py
      - artifacts/features/test.pkl
      - src/utils/common.py
      - configs/configs.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  run_plots_command:
    cmd: dvc plots diff
